version: '2'
services:
  web:
    container_name: test-api-server
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      MYSQL_HOST: ${MYSQL_HOST}
      TEST_DB_USER: ${TEST_DB_USER}
      TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: "./johnny-app-dev-firebase-adminsdk-8q1im-6b2b072cc2.json"
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  database:
    image: mysql:8.0
    container_name: test-db
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database_conf/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}

networks:
  default:
    external:
      name: ${TEST_NETWORK_NAME}
